export declare type OmegaNumJSON = {
    array: number[];
    sign: number;
};
export declare type OmegaNumSource = number | string | number[] | OmegaNumJSON | OmegaNum;
export default class OmegaNum {
    static maxArrow: number;
    static serializeMode: number;
    static debug: number;
    static readonly ZERO: OmegaNum;
    static readonly ONE: OmegaNum;
    static readonly E: OmegaNum;
    static readonly LN2: OmegaNum;
    static readonly LN10: OmegaNum;
    static readonly LOG2E: OmegaNum;
    static readonly LOG10E: OmegaNum;
    static readonly PI: OmegaNum;
    static readonly SQRT1_2: OmegaNum;
    static readonly SQRT2: OmegaNum;
    static readonly MAX_SAFE_INTEGER: OmegaNum;
    static readonly MIN_SAFE_INTEGER: OmegaNum;
    static readonly NaN: OmegaNum;
    static readonly NEGATIVE_INFINITY: OmegaNum;
    static readonly POSITIVE_INFINITY: OmegaNum;
    static readonly E_MAX_SAFE_INTEGER: OmegaNum;
    static readonly EE_MAX_SAFE_INTEGER: OmegaNum;
    static readonly TETRATED_MAX_SAFE_INTEGER: OmegaNum;
    array: number[];
    sign: number;
    abs(): OmegaNum;
    absoluteValue(): OmegaNum;
    static abs(x: OmegaNumSource | undefined): OmegaNum;
    static absoluteValue(x: OmegaNumSource | undefined): OmegaNum;
    neg(): OmegaNum;
    negate(): OmegaNum;
    static neg(x: OmegaNumSource | undefined): OmegaNum;
    static negate(x: OmegaNumSource | undefined): OmegaNum;
    cmp(other: OmegaNumSource | undefined): number;
    compareTo(other: OmegaNumSource | undefined): number;
    static cmp(x: OmegaNumSource | undefined, y: OmegaNumSource | undefined): number;
    static compare(x: OmegaNumSource | undefined, y: OmegaNumSource | undefined): number;
    gt(other: OmegaNumSource | undefined): boolean;
    greaterThan(other: OmegaNumSource | undefined): boolean;
    static gt(x: OmegaNumSource | undefined, y: OmegaNumSource | undefined): boolean;
    static greaterThan(x: OmegaNumSource | undefined, y: OmegaNumSource | undefined): boolean;
    gte(other: OmegaNumSource | undefined): boolean;
    greaterThanOrEqualTo(other: OmegaNumSource | undefined): boolean;
    static gte(x: OmegaNumSource | undefined, y: OmegaNumSource | undefined): boolean;
    static greaterThanOrEqualTo(x: OmegaNumSource | undefined, y: OmegaNumSource | undefined): boolean;
    lt(other: OmegaNumSource | undefined): boolean;
    lessThan(other: OmegaNumSource | undefined): boolean;
    static lt(x: OmegaNumSource | undefined, y: OmegaNumSource | undefined): boolean;
    static lessThan(x: OmegaNumSource | undefined, y: OmegaNumSource | undefined): boolean;
    lte(other: OmegaNumSource | undefined): boolean;
    lessThanOrEqualTo(other: OmegaNumSource | undefined): boolean;
    static lte(x: OmegaNumSource | undefined, y: OmegaNumSource | undefined): boolean;
    static lessThanOrEqualTo(x: OmegaNumSource | undefined, y: OmegaNumSource | undefined): boolean;
    eq(other: OmegaNumSource | undefined): boolean;
    equal(other: OmegaNumSource | undefined): boolean;
    equalsTo(other: OmegaNumSource | undefined): boolean;
    static eq(x: OmegaNumSource | undefined, y: OmegaNumSource | undefined): boolean;
    static equal(x: OmegaNumSource | undefined, y: OmegaNumSource | undefined): boolean;
    static equalsTo(x: OmegaNumSource | undefined, y: OmegaNumSource | undefined): boolean;
    neq(other: OmegaNumSource | undefined): boolean;
    notEqual(other: OmegaNumSource | undefined): boolean;
    notEqualsTo(other: OmegaNumSource | undefined): boolean;
    static neq(x: OmegaNumSource | undefined, y: OmegaNumSource | undefined): boolean;
    static notEqual(x: OmegaNumSource | undefined, y: OmegaNumSource | undefined): boolean;
    static notEqualsTo(x: OmegaNumSource | undefined, y: OmegaNumSource | undefined): boolean;
    min(other: OmegaNumSource | undefined): OmegaNum;
    minimum(other: OmegaNumSource | undefined): OmegaNum;
    static min(x: OmegaNumSource | undefined, y: OmegaNumSource | undefined): OmegaNum;
    static minimum(x: OmegaNumSource | undefined, y: OmegaNumSource | undefined): OmegaNum;
    max(other: OmegaNumSource | undefined): OmegaNum;
    maximum(other: OmegaNumSource | undefined): OmegaNum;
    static max(x: OmegaNumSource | undefined, y: OmegaNumSource | undefined): OmegaNum;
    static maximum(x: OmegaNumSource | undefined, y: OmegaNumSource | undefined): OmegaNum;
    ispos(): boolean;
    isPositive(): boolean;
    static ispos(x: OmegaNumSource | undefined): boolean;
    static isPositive(x: OmegaNumSource | undefined): boolean;
    isneg(): boolean;
    isNegative(): boolean;
    static isneg(x: OmegaNumSource | undefined): boolean;
    static isNegative(x: OmegaNumSource | undefined): boolean;
    isNaN(): boolean;
    static isNaN(x: OmegaNumSource | undefined): boolean;
    isFinite(): boolean;
    static isFinite(x: OmegaNumSource | undefined): boolean;
    isInfinite(): boolean;
    static isInfinite(x: OmegaNumSource | undefined): boolean;
    isint(): boolean;
    isInteger(): boolean;
    static isint(x: OmegaNumSource | undefined): boolean;
    static isInteger(x: OmegaNumSource | undefined): boolean;
    floor(): OmegaNum;
    static floor(x: OmegaNumSource | undefined): OmegaNum;
    ceil(): OmegaNum;
    ceiling(): OmegaNum;
    static ceil(x: OmegaNumSource | undefined): OmegaNum;
    static ceiling(x: OmegaNumSource | undefined): OmegaNum;
    round(): OmegaNum;
    static round(x: OmegaNumSource | undefined): OmegaNum;
    add(otherIn: OmegaNumSource | undefined): OmegaNum;
    plus(other: OmegaNumSource | undefined): OmegaNum;
    static add(x: OmegaNumSource | undefined, y: OmegaNumSource | undefined): OmegaNum;
    static plus(x: OmegaNumSource | undefined, y: OmegaNumSource | undefined): OmegaNum;
    sub(otherIn: OmegaNumSource | undefined): OmegaNum;
    minus(other: OmegaNumSource | undefined): OmegaNum;
    static sub(x: OmegaNumSource | undefined, y: OmegaNumSource | undefined): OmegaNum;
    static minus(x: OmegaNumSource | undefined, y: OmegaNumSource | undefined): OmegaNum;
    mul(otherIn: OmegaNumSource | undefined): OmegaNum;
    times(other: OmegaNumSource | undefined): OmegaNum;
    static mul(x: OmegaNumSource | undefined, y: OmegaNumSource | undefined): OmegaNum;
    static times(x: OmegaNumSource | undefined, y: OmegaNumSource | undefined): OmegaNum;
    div(otherIn: OmegaNumSource | undefined): OmegaNum;
    divide(other: OmegaNumSource | undefined): OmegaNum;
    static div(x: OmegaNumSource | undefined, y: OmegaNumSource | undefined): OmegaNum;
    static divide(x: OmegaNumSource | undefined, y: OmegaNumSource | undefined): OmegaNum;
    rec(): OmegaNum;
    reciprocate(): OmegaNum;
    static rec(x: OmegaNumSource | undefined): OmegaNum;
    static reciprocate(x: OmegaNumSource | undefined): OmegaNum;
    mod(otherIn: OmegaNumSource | undefined): OmegaNum;
    modular(other: OmegaNumSource | undefined): OmegaNum;
    static mod(x: OmegaNumSource | undefined, y: OmegaNumSource | undefined): OmegaNum;
    static modular(x: OmegaNumSource | undefined, y: OmegaNumSource | undefined): OmegaNum;
    gamma(): OmegaNum;
    static gamma(x: OmegaNumSource | undefined): OmegaNum;
    static factorials: number[];
    fact(): OmegaNum;
    factorial(): OmegaNum;
    static fact(x: OmegaNumSource | undefined): OmegaNum;
    static factorial(x: OmegaNumSource | undefined): OmegaNum;
    pow(otherIn: OmegaNumSource | undefined): OmegaNum;
    toPower(other: OmegaNumSource | undefined): OmegaNum;
    static pow(x: OmegaNumSource | undefined, y: OmegaNumSource | undefined): OmegaNum;
    static toPower(x: OmegaNumSource | undefined, y: OmegaNumSource | undefined): OmegaNum;
    exp(): OmegaNum;
    exponential(): OmegaNum;
    static exp(x: OmegaNumSource | undefined): OmegaNum;
    static exponential(x: OmegaNumSource | undefined): OmegaNum;
    sqrt(): OmegaNum;
    squareRoot(): OmegaNum;
    static sqrt(x: OmegaNumSource | undefined): OmegaNum;
    static squareRoot(x: OmegaNumSource | undefined): OmegaNum;
    cbrt(): OmegaNum;
    cubeRoot(): OmegaNum;
    static cbrt(x: OmegaNumSource | undefined): OmegaNum;
    static cubeRoot(x: OmegaNumSource | undefined): OmegaNum;
    root(otherIn: OmegaNumSource | undefined): OmegaNum;
    static root(x: OmegaNumSource | undefined, y: OmegaNumSource | undefined): OmegaNum;
    log10(): OmegaNum;
    generalLogarithm(): OmegaNum;
    static log10(x: OmegaNumSource | undefined): OmegaNum;
    static generalLogarithm(x: OmegaNumSource | undefined): OmegaNum;
    logBase(base?: OmegaNumSource | undefined): OmegaNum;
    logarithm(base?: OmegaNumSource | undefined): OmegaNum;
    static logBase(x: OmegaNumSource | undefined, base?: OmegaNumSource | undefined): OmegaNum;
    static logarithm(x: OmegaNumSource | undefined, base?: OmegaNumSource | undefined): OmegaNum;
    ln(): OmegaNum;
    log(): OmegaNum;
    naturalLogarithm(): OmegaNum;
    static ln(x: OmegaNumSource | undefined): OmegaNum;
    static log(x: OmegaNumSource | undefined): OmegaNum;
    static naturalLogarithm(x: OmegaNumSource | undefined): OmegaNum;
    lambertw(): OmegaNum;
    static lambertw(x: OmegaNumSource | undefined): OmegaNum;
    tetr(otherIn: OmegaNumSource | undefined, payloadIn?: OmegaNumSource | undefined): OmegaNum;
    tetrate(other: OmegaNumSource | undefined, payload?: OmegaNumSource | undefined): OmegaNum;
    static tetr(x: OmegaNumSource | undefined, y: OmegaNumSource | undefined, payload?: OmegaNumSource | undefined): OmegaNum;
    static tetrate(x: OmegaNumSource | undefined, y: OmegaNumSource | undefined, payload?: OmegaNumSource | undefined): OmegaNum;
    iteratedexp(other: OmegaNumSource | undefined, payload?: OmegaNumSource | undefined): OmegaNum;
    static iteratedexp(x: OmegaNumSource | undefined, y: OmegaNumSource | undefined, payload?: OmegaNumSource | undefined): OmegaNum;
    iteratedlog(baseIn?: OmegaNumSource | undefined, otherIn?: OmegaNumSource | undefined): OmegaNum;
    static iteratedlog(x: OmegaNumSource | undefined, y?: OmegaNumSource | undefined, z?: OmegaNumSource | undefined): OmegaNum;
    layeradd(otherIn?: OmegaNumSource | undefined, baseIn?: OmegaNumSource | undefined): OmegaNum;
    static layeradd(x: OmegaNumSource | undefined, y?: OmegaNumSource | undefined, z?: OmegaNumSource | undefined): OmegaNum;
    layeradd10(other?: OmegaNumSource | undefined): OmegaNum;
    static layeradd10(x: OmegaNumSource | undefined, y?: OmegaNumSource | undefined): OmegaNum;
    ssrt(): OmegaNum;
    ssqrt(): OmegaNum;
    static ssrt(x: OmegaNumSource | undefined): OmegaNum;
    static ssqrt(x: OmegaNumSource | undefined): OmegaNum;
    slog(baseIn?: OmegaNumSource | undefined): OmegaNum;
    static slog(x: OmegaNumSource | undefined, y?: OmegaNumSource | undefined): OmegaNum;
    pent(other: OmegaNumSource | undefined): OmegaNum;
    pentate(other: OmegaNumSource | undefined): OmegaNum;
    static pent(x: OmegaNumSource | undefined, y: OmegaNumSource | undefined): OmegaNum;
    static pentate(x: OmegaNumSource | undefined, y: OmegaNumSource | undefined): OmegaNum;
    arrow(arrowsIn: OmegaNumSource | undefined): ((other: OmegaNumSource | undefined) => OmegaNum);
    chain(other: OmegaNumSource | undefined, arrows: OmegaNumSource | undefined): OmegaNum;
    static arrow(x: OmegaNumSource | undefined, z: OmegaNumSource | undefined, y: OmegaNumSource | undefined): OmegaNum;
    static chain(x: OmegaNumSource | undefined, y: OmegaNumSource | undefined, z: OmegaNumSource | undefined): OmegaNum;
    static hyper(zIn: OmegaNumSource | undefined): (x: OmegaNumSource | undefined, y: OmegaNumSource | undefined) => OmegaNum;
    static affordGeometricSeries(resourcesAvailableIn: OmegaNumSource | undefined, priceStartIn: OmegaNumSource | undefined, priceRatioIn: OmegaNumSource | undefined, currentOwned: OmegaNumSource | undefined): OmegaNum;
    static affordArithmeticSeries(resourcesAvailableIn: OmegaNumSource | undefined, priceStartIn: OmegaNumSource | undefined, priceAddIn: OmegaNumSource | undefined, currentOwnedIn: OmegaNumSource | undefined): OmegaNum;
    static sumGeometricSeries(numItems: OmegaNumSource | undefined, priceStartIn: OmegaNumSource | undefined, priceRatioIn: OmegaNumSource | undefined, currentOwned: OmegaNumSource | undefined): OmegaNum;
    static sumArithmeticSeries(numItemsIn: OmegaNumSource | undefined, priceStartIn: OmegaNumSource | undefined, priceAdd: OmegaNumSource | undefined, currentOwnedIn: OmegaNumSource | undefined): OmegaNum;
    static choose(n: OmegaNumSource | undefined, k: OmegaNumSource | undefined): OmegaNum;
    choose(other: OmegaNumSource | undefined): OmegaNum;
    standardize(): this;
    toNumber(): number;
    toString(): string;
    toStringWithDecimalPlaces(places: number, applyToOpNums: boolean): string;
    toExponential(places: number, applyToOpNums: boolean): string;
    toFixed(places: number, applyToOpNums: boolean): string;
    toPrecision(places: number, applyToOpNums: boolean): string;
    valueOf(): string;
    toJSON(): string | {
        array: number[];
        sign: number;
    } | undefined;
    toHyperE(): string;
    static fromNumber(input: number): OmegaNum;
    static fromString(input: string): OmegaNum;
    static fromArray(input1: number[], input2?: number): OmegaNum;
    static fromArray(input1: number, input2: number[]): OmegaNum;
    static fromObject(input: number[] | OmegaNumJSON | OmegaNum): OmegaNum;
    static fromJSON(input: string | OmegaNumJSON): OmegaNum;
    static fromHyperE(input: string): OmegaNum;
    clone(): OmegaNum;
    constructor(input?: OmegaNumSource, input2?: undefined);
    constructor(input: number, input2: number[]);
    static readonly JSON = 0;
    static readonly STRING = 1;
    static readonly NONE = 0;
    static readonly NORMAL = 1;
    static readonly ALL = 2;
    static config(obj: {
        [x: string]: number;
    }): typeof OmegaNum;
    static get default(): typeof OmegaNum;
    static get OmegaNum(): typeof OmegaNum;
    static set(obj: {
        [x: string]: number;
    }): void;
}
